//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT
{


    public partial class MasterPageUser
    {

        /// <summary>
        /// head control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// txtTuKhoa control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTuKhoa;

        /// <summary>
        /// btnTimKiem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ImageButton btnTimKiem;

        /// <summary>
        /// phChuaDangNhap control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phChuaDangNhap;

        /// <summary>
        /// phDaDangNhap control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phDaDangNhap;

        /// <summary>
        /// litHoTen control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHoTen;

        /// <summary>
        /// rptDANHMUC control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDANHMUC;

        /// <summary>
        /// ContentPlaceHolder1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;

        /// <summary>
        /// litSoLuongGioHang control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSoLuongGioHang;

        /// <summary>
        /// litTongTienGioHang control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTongTienGioHang;
    }
}
