//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT
{


    public partial class pageLOGIN
    {

        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Content Content2;
        protected global::System.Web.UI.WebControls.TextBox txtUserName;
        protected global::System.Web.UI.WebControls.TextBox txtPassWord;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Label lblLoi;
    }
}
