//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT
{


    public partial class pageDANGKY
    {

        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Content Content2;
        protected global::System.Web.UI.WebControls.TextBox txtTENDANGNHAP;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTDN;
        protected global::System.Web.UI.WebControls.TextBox txtMATKHAU;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMK;
        protected global::System.Web.UI.WebControls.TextBox txtNHAPLAIMATKHAU;
        protected global::System.Web.UI.WebControls.CompareValidator cvMK;
        protected global::System.Web.UI.WebControls.TextBox txtHOTEN;
        protected global::System.Web.UI.WebControls.TextBox txtEMAIL;
        protected global::System.Web.UI.WebControls.TextBox txtDIENTHOAI;
        protected global::System.Web.UI.WebControls.TextBox txtDIACHI;
        protected global::System.Web.UI.WebControls.Button btnDangKy;
        protected global::System.Web.UI.WebControls.Label lblThongBao;
    }
}
