/* ================================================================
   CSDL: dbQUANLYBANHANG
   Dự án: QUẢN LÝ BÁN HÀNG TRỰC TUYẾN (QUANLYBANHANG_ONLINE_NBT)
   Cách dùng: Mở SQL Server Management Studio (SSMS) -> New Query
              -> Paste toàn bộ file này -> Execute (F5)
   ================================================================ */

IF DB_ID('dbQUANLYBANHANG') IS NULL
BEGIN
    CREATE DATABASE dbQUANLYBANHANG;
END
GO

USE dbQUANLYBANHANG;
GO

/* ================== XÓA BẢNG/PROC CŨ (NẾU CHẠY LẠI) ================== */
IF OBJECT_ID('dbo.CTDONHANG','U') IS NOT NULL DROP TABLE dbo.CTDONHANG;
IF OBJECT_ID('dbo.DONHANG','U')   IS NOT NULL DROP TABLE dbo.DONHANG;
IF OBJECT_ID('dbo.SANPHAM','U')   IS NOT NULL DROP TABLE dbo.SANPHAM;
IF OBJECT_ID('dbo.DANHMUC','U')   IS NOT NULL DROP TABLE dbo.DANHMUC;
IF OBJECT_ID('dbo.TAIKHOAN','U')  IS NOT NULL DROP TABLE dbo.TAIKHOAN;
GO

/* ============================ BẢNG DỮ LIỆU ============================ */

CREATE TABLE DANHMUC (
    MADANHMUC   INT IDENTITY(1,1) PRIMARY KEY,
    TENDANHMUC  NVARCHAR(100) NOT NULL,
    MOTA        NVARCHAR(255) NULL
);
GO

CREATE TABLE SANPHAM (
    MASANPHAM   INT IDENTITY(1,1) PRIMARY KEY,
    TENSANPHAM  NVARCHAR(150) NOT NULL,
    DONGIA      DECIMAL(18,2) NOT NULL DEFAULT 0,
    SOLUONG     INT NOT NULL DEFAULT 0,
    HINHANH     NVARCHAR(255) NULL,
    MOTA        NVARCHAR(MAX) NULL,
    MADANHMUC   INT NULL,
    CONSTRAINT FK_SANPHAM_DANHMUC FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC(MADANHMUC)
);
GO

CREATE TABLE TAIKHOAN (
    TENDANGNHAP NVARCHAR(50) PRIMARY KEY,
    MATKHAU     NVARCHAR(50) NOT NULL,
    HOTEN       NVARCHAR(100) NULL,
    EMAIL       NVARCHAR(100) NULL,
    DIENTHOAI   NVARCHAR(20) NULL,
    DIACHI      NVARCHAR(255) NULL,
    QUYEN       BIT NOT NULL DEFAULT 0   -- 0 = khách hàng, 1 = quản trị
);
GO

CREATE TABLE DONHANG (
    MADONHANG       INT IDENTITY(1,1) PRIMARY KEY,
    TENDANGNHAP     NVARCHAR(50) NULL,
    HOTENNGUOINHAN  NVARCHAR(100) NOT NULL,
    DIACHINHAN      NVARCHAR(255) NOT NULL,
    DIENTHOAINHAN   NVARCHAR(20) NOT NULL,
    NGAYDAT         DATETIME NOT NULL DEFAULT GETDATE(),
    TONGTIEN        DECIMAL(18,2) NOT NULL DEFAULT 0,
    TRANGTHAI       NVARCHAR(50) NOT NULL DEFAULT N'Chờ xử lý',
    CONSTRAINT FK_DONHANG_TAIKHOAN FOREIGN KEY (TENDANGNHAP) REFERENCES TAIKHOAN(TENDANGNHAP)
);
GO

CREATE TABLE CTDONHANG (
    MADONHANG   INT NOT NULL,
    MASANPHAM   INT NOT NULL,
    TENSANPHAM  NVARCHAR(150) NOT NULL,
    SOLUONG     INT NOT NULL,
    DONGIA      DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_CTDONHANG PRIMARY KEY (MADONHANG, MASANPHAM),
    CONSTRAINT FK_CTDONHANG_DONHANG FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG)
);
GO

/* ============================ DỮ LIỆU MẪU ============================ */

INSERT INTO DANHMUC (TENDANHMUC, MOTA) VALUES
(N'Laptops & Notebooks', N'Máy tính xách tay'),
(N'Desktops', N'Máy tính để bàn'),
(N'Processors', N'Bộ vi xử lý'),
(N'Motherboards', N'Bo mạch chủ');
GO

INSERT INTO SANPHAM (TENSANPHAM, DONGIA, SOLUONG, HINHANH, MOTA, MADANHMUC) VALUES
(N'Motorola 156 MX-VL', 270, 20, 'laptop.png', N'Laptop mỏng nhẹ, hiệu năng ổn định, phù hợp học tập và làm việc văn phòng.', 1),
(N'Samsung GX 2004 LM', 350, 15, 'laptop.gif', N'Thiết kế sang trọng, màn hình sắc nét, pin bền bỉ.', 1),
(N'iPhone Style Ultrabook', 480, 10, 'iphone.png', N'Cấu hình mạnh, thiết kế hiện đại.', 1),
(N'Desktop Combo Pro', 300, 8, 'latop.png', N'Bộ máy tính để bàn cấu hình khá, phù hợp văn phòng.', 2);
GO

-- Tài khoản quản trị mặc định: admin / 123456
INSERT INTO TAIKHOAN (TENDANGNHAP, MATKHAU, HOTEN, EMAIL, DIENTHOAI, DIACHI, QUYEN) VALUES
('admin', '123456', N'Quản trị viên', 'admin@electronix.com', '0900000000', N'Việt Nam', 1);
GO

/* ========================= STORED PROCEDURES ========================= */

-- ===== DANH MỤC =====
CREATE OR ALTER PROCEDURE psGetTableDANHMUC
    @MADANHMUC INT = NULL
AS
BEGIN
    IF @MADANHMUC IS NULL
        SELECT * FROM DANHMUC ORDER BY TENDANHMUC;
    ELSE
        SELECT * FROM DANHMUC WHERE MADANHMUC = @MADANHMUC;
END
GO

CREATE OR ALTER PROCEDURE psInsertRecordDANHMUC
    @TENDANHMUC NVARCHAR(100),
    @MOTA NVARCHAR(255) = NULL
AS
BEGIN
    INSERT INTO DANHMUC(TENDANHMUC, MOTA) VALUES(@TENDANHMUC, @MOTA);
END
GO

CREATE OR ALTER PROCEDURE psUpdateRecordDANHMUC
    @MADANHMUC INT,
    @TENDANHMUC NVARCHAR(100),
    @MOTA NVARCHAR(255) = NULL
AS
BEGIN
    UPDATE DANHMUC SET TENDANHMUC = @TENDANHMUC, MOTA = @MOTA WHERE MADANHMUC = @MADANHMUC;
END
GO

CREATE OR ALTER PROCEDURE psDeleteRecordDANHMUC
    @MADANHMUC INT
AS
BEGIN
    DELETE FROM DANHMUC WHERE MADANHMUC = @MADANHMUC;
END
GO

-- ===== SẢN PHẨM =====
CREATE OR ALTER PROCEDURE psGetTableSANPHAM
    @MASANPHAM INT = NULL
AS
BEGIN
    IF @MASANPHAM IS NULL
        SELECT * FROM SANPHAM ORDER BY MASANPHAM DESC;
    ELSE
        SELECT * FROM SANPHAM WHERE MASANPHAM = @MASANPHAM;
END
GO

CREATE OR ALTER PROCEDURE psGetTableSanPhamTheoDanhMuc
    @MADANHMUC INT
AS
BEGIN
    SELECT * FROM SANPHAM WHERE MADANHMUC = @MADANHMUC ORDER BY MASANPHAM DESC;
END
GO

CREATE OR ALTER PROCEDURE psInsertRecordSANPHAM
    @TENSANPHAM NVARCHAR(150),
    @DONGIA DECIMAL(18,2),
    @SOLUONG INT,
    @HINHANH NVARCHAR(255) = NULL,
    @MOTA NVARCHAR(MAX) = NULL,
    @MADANHMUC INT = NULL
AS
BEGIN
    INSERT INTO SANPHAM(TENSANPHAM, DONGIA, SOLUONG, HINHANH, MOTA, MADANHMUC)
    VALUES(@TENSANPHAM, @DONGIA, @SOLUONG, @HINHANH, @MOTA, @MADANHMUC);
END
GO

CREATE OR ALTER PROCEDURE psUpdateRecordSANPHAM
    @MASANPHAM INT,
    @TENSANPHAM NVARCHAR(150),
    @DONGIA DECIMAL(18,2),
    @SOLUONG INT,
    @HINHANH NVARCHAR(255) = NULL,
    @MOTA NVARCHAR(MAX) = NULL,
    @MADANHMUC INT = NULL
AS
BEGIN
    UPDATE SANPHAM SET
        TENSANPHAM = @TENSANPHAM,
        DONGIA = @DONGIA,
        SOLUONG = @SOLUONG,
        HINHANH = ISNULL(@HINHANH, HINHANH),
        MOTA = @MOTA,
        MADANHMUC = @MADANHMUC
    WHERE MASANPHAM = @MASANPHAM;
END
GO

CREATE OR ALTER PROCEDURE psDeleteRecordSANPHAM
    @MASANPHAM INT
AS
BEGIN
    DELETE FROM SANPHAM WHERE MASANPHAM = @MASANPHAM;
END
GO

CREATE OR ALTER PROCEDURE psTimKiemSanPham
    @TUKHOA NVARCHAR(150)
AS
BEGIN
    SELECT * FROM SANPHAM WHERE TENSANPHAM LIKE '%' + @TUKHOA + '%' ORDER BY MASANPHAM DESC;
END
GO

-- ===== TÀI KHOẢN / ĐĂNG NHẬP =====
CREATE OR ALTER PROCEDURE psgetTableLOGIN
    @TENDANGNHAP NVARCHAR(50),
    @MATKHAU NVARCHAR(50)
AS
BEGIN
    SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP AND MATKHAU = @MATKHAU;
END
GO

CREATE OR ALTER PROCEDURE psKiemTraTonTaiTaiKhoan
    @TENDANGNHAP NVARCHAR(50)
AS
BEGIN
    SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP;
END
GO

CREATE OR ALTER PROCEDURE psInsertRecordTAIKHOAN
    @TENDANGNHAP NVARCHAR(50),
    @MATKHAU NVARCHAR(50),
    @HOTEN NVARCHAR(100) = NULL,
    @EMAIL NVARCHAR(100) = NULL,
    @DIENTHOAI NVARCHAR(20) = NULL,
    @DIACHI NVARCHAR(255) = NULL
AS
BEGIN
    INSERT INTO TAIKHOAN(TENDANGNHAP, MATKHAU, HOTEN, EMAIL, DIENTHOAI, DIACHI, QUYEN)
    VALUES(@TENDANGNHAP, @MATKHAU, @HOTEN, @EMAIL, @DIENTHOAI, @DIACHI, 0);
END
GO

-- ===== ĐƠN HÀNG =====
CREATE OR ALTER PROCEDURE psInsertRecordDONHANG
    @TENDANGNHAP NVARCHAR(50) = NULL,
    @HOTENNGUOINHAN NVARCHAR(100),
    @DIACHINHAN NVARCHAR(255),
    @DIENTHOAINHAN NVARCHAR(20),
    @TONGTIEN DECIMAL(18,2)
AS
BEGIN
    INSERT INTO DONHANG(TENDANGNHAP, HOTENNGUOINHAN, DIACHINHAN, DIENTHOAINHAN, TONGTIEN)
    VALUES(@TENDANGNHAP, @HOTENNGUOINHAN, @DIACHINHAN, @DIENTHOAINHAN, @TONGTIEN);

    SELECT SCOPE_IDENTITY() AS MADONHANG;
END
GO

CREATE OR ALTER PROCEDURE psInsertRecordCTDONHANG
    @MADONHANG INT,
    @MASANPHAM INT,
    @TENSANPHAM NVARCHAR(150),
    @SOLUONG INT,
    @DONGIA DECIMAL(18,2)
AS
BEGIN
    INSERT INTO CTDONHANG(MADONHANG, MASANPHAM, TENSANPHAM, SOLUONG, DONGIA)
    VALUES(@MADONHANG, @MASANPHAM, @TENSANPHAM, @SOLUONG, @DONGIA);
END
GO

CREATE OR ALTER PROCEDURE psGetTableDONHANG
    @MADONHANG INT = NULL
AS
BEGIN
    IF @MADONHANG IS NULL
        SELECT * FROM DONHANG ORDER BY NGAYDAT DESC;
    ELSE
        SELECT * FROM DONHANG WHERE MADONHANG = @MADONHANG;
END
GO

CREATE OR ALTER PROCEDURE psGetTableCTDONHANG
    @MADONHANG INT
AS
BEGIN
    SELECT * FROM CTDONHANG WHERE MADONHANG = @MADONHANG;
END
GO

CREATE OR ALTER PROCEDURE psUpdateTrangThaiDONHANG
    @MADONHANG INT,
    @TRANGTHAI NVARCHAR(50)
AS
BEGIN
    UPDATE DONHANG SET TRANGTHAI = @TRANGTHAI WHERE MADONHANG = @MADONHANG;
END
GO

PRINT N'Đã tạo xong CSDL dbQUANLYBANHANG.';
