//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT.ADMIN.GUI
{


    public partial class QUANLYSANPHAM_GUI
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtMASANPHAM;
        protected global::System.Web.UI.WebControls.TextBox txtTENSANPHAM;
        protected global::System.Web.UI.WebControls.DropDownList drpDANHMUC;
        protected global::System.Web.UI.WebControls.TextBox txtDONGIA;
        protected global::System.Web.UI.WebControls.TextBox txtSOLUONG;
        protected global::System.Web.UI.WebControls.TextBox txtMOTA;
        protected global::System.Web.UI.WebControls.FileUpload FileANHSANPHAM;
        protected global::System.Web.UI.WebControls.Literal litHINHANHHIENTAI;
        protected global::System.Web.UI.WebControls.Button btnMakeNew;
        protected global::System.Web.UI.WebControls.Button btnInsert;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Label lblThongBao;
        protected global::System.Web.UI.WebControls.GridView grvSANPHAM;
    }
}
