//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT.ADMIN.GUI
{


    public partial class QUANLYDANHMUC_GUI
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtMADANHMUC;
        protected global::System.Web.UI.WebControls.TextBox txtTENDANHMUC;
        protected global::System.Web.UI.WebControls.TextBox txtMOTA;
        protected global::System.Web.UI.WebControls.Button btnMakeNew;
        protected global::System.Web.UI.WebControls.Button btnInsert;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Label lblThongBao;
        protected global::System.Web.UI.WebControls.GridView grvDANHMUC;
    }
}
