//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT.ADMIN.GUI
{


    public partial class TRANGCHU_ADMIN
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litHoTen;
        protected global::System.Web.UI.WebControls.Literal litSoSanPham;
        protected global::System.Web.UI.WebControls.Literal litSoDanhMuc;
        protected global::System.Web.UI.WebControls.Literal litSoDonHang;
    }
}
