//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT
{


    public partial class CHITIETSANPHAM
    {

        /// <summary>
        /// Content1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content Content1;

        /// <summary>
        /// Content2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content Content2;

        /// <summary>
        /// rptCHITIET control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCHITIET;

        /// <summary>
        /// lblThongBao control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblThongBao;
    }
}
