//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT
{


    public partial class pageGIOHANG
    {

        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Content Content2;
        protected global::System.Web.UI.WebControls.GridView grvCART;
        protected global::System.Web.UI.WebControls.Literal litTongCong;
        protected global::System.Web.UI.WebControls.TextBox txtHOTENNGUOINHAN;
        protected global::System.Web.UI.WebControls.TextBox txtDIACHINHAN;
        protected global::System.Web.UI.WebControls.TextBox txtDIENTHOAINHAN;
        protected global::System.Web.UI.WebControls.Button btnDatHang;
        protected global::System.Web.UI.WebControls.Button btnXoaGioHang;
        protected global::System.Web.UI.WebControls.Label lblThongBao;
    }
}
