//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_ONLINE_NBT.ADMIN.GUI
{


    public partial class QUANLYDONHANG_GUI
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView grvDONHANG;
        protected global::System.Web.UI.WebControls.Label lblMaDonHangDangXem;
        protected global::System.Web.UI.WebControls.GridView grvCHITIETDONHANG;
        protected global::System.Web.UI.WebControls.Label lblThongBao;
    }
}
